service: serverless-app

package:
  individually: true

provider:
  name: aws
  runtime: python3.6
  region: us-east-1
  stage: ${opt:stage, "dev"}
  profile: ${opt:aws-profile}

plugins:
  - serverless-python-requirements
custom:
  pythonRequirements:
    dockerizePip: true
    layer:
      name: serverless-app-layer
      description: serverless-app layer
      compatibleRuntimes:
        - python3.6

functions:
  app:
    package:
      include:
        - "main.py"
      exclude:
        - "requirements.txt"
        - "package.json"
        - "package-lock.json"
        - ".serverless/**"
        - ".virtualenv/**"
        - "node_modules/**"
    handler: main.handler
    environment:
      STAGE: ${self:provider.stage}
    layers:
      - { Ref: PythonRequirementsLambdaLayer }
    events:
      - http:
          method: any
          path: /{proxy+}